services:
  review:
    restart: unless-stopped
    build:
      context: .
      dockerfile: base-dockerfile
    healthcheck:
      test: wget -qO - http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      review-db:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://review-db:27017
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  review-db:
    image: mongo
    volumes:
      - review-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
    command: --quiet
  review-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "review",
        "--app-port",
        "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
        "--app-protocol",
        "http",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]
    network_mode: "service:review"
volumes:
  review-db-data:
