services:
  review:
    restart: unless-stopped
    build:
      context: .
      dockerfile: base-dockerfile
    healthcheck:
      test: wget http://localhost:8080/graphiql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      review-db:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://review-db:27017
  review-db:
    image: mongo
    volumes:
      - review-db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
  review-dapr:
    image: "daprio/daprd:edge"
    command:
      [
        "./daprd",
        "--app-id",
        "review",
        "--app-port",
        "50051",
        "--app-protocol",
        "grpc",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]
    network_mode: "service:review"
volumes:
  review-db-data:
